# Generated by Django 4.1.3 on 2022-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_by", models.CharField(max_length=50)),
                ("post_date", models.DateTimeField(auto_now_add=True)),
                ("post_text", models.TextField(max_length=500)),
            ],
        ),
    ]
